# Copyright (c) 2023 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file ./server/dialect-example/pom.xml

    - name: Package vsix
        run: |
          cp ./server/dialect-example/target/dialect-example.jar ./client/example-dialect-support/server/jar
          npm --prefix ./client/example-dialect-support/ ci
          npm --prefix ./client/example-dialect-support/ run package -- -o ./vsix/dialect-example.vsix
          
    - name: Upload vsix
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: warn
          name: vsix-dialect-template
          path: './vsix/dialect-example.vsix'
